package xxtf.oracle.apps.xxtf.restdemo.server;

import oracle.apps.fnd.framework.server.OAEntityDefImpl;
import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RestInvoiceEOImpl extends OAEntityImpl {
  public static final int INVOICEID = 0;
  public static final int INVOICENUM = 1;
  public static final int INVOICEDATE = 2;
  public static final int CUSTOMERNUM = 3;
  public static final int CREATEDBY = 4;
  public static final int CREATIONDATE = 5;
  public static final int LASTUPDATEDBY = 6;
  public static final int LASTUPDATEDATE = 7;
  public static final int LASTUPDATELOGIN = 8;
  public static final int RESTINVOICELINEEO = 9;


  private static OAEntityDefImpl mDefinitionObject;

  /**This is the default constructor (do not remove)
   */
  public RestInvoiceEOImpl() {
  }


  /**Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject() {
    if (mDefinitionObject == null) {
      mDefinitionObject = 
          (OAEntityDefImpl)EntityDefImpl.findDefObject("xxtf.oracle.apps.xxtf.restdemo.server.RestInvoiceEO");
    }
    return mDefinitionObject;
  }

  /**Add attribute defaulting logic in this method.
   */
  public void create(AttributeList attributeList) {
    super.create(attributeList);
    setInvoiceId(getOADBTransaction().getSequenceValue("XXTF_REST_INVOICES_S"));
  }

  /**Gets the attribute value for InvoiceId, using the alias name InvoiceId
   */
  public Number getInvoiceId() {
    return (Number)getAttributeInternal(INVOICEID);
  }

  /**Sets <code>value</code> as the attribute value for InvoiceId
   */
  public void setInvoiceId(Number value) {
    setAttributeInternal(INVOICEID, value);
  }

  /**Gets the attribute value for InvoiceNum, using the alias name InvoiceNum
   */
  public String getInvoiceNum() {
    return (String)getAttributeInternal(INVOICENUM);
  }

  /**Sets <code>value</code> as the attribute value for InvoiceNum
   */
  public void setInvoiceNum(String value) {
    setAttributeInternal(INVOICENUM, value);
  }

  /**Gets the attribute value for InvoiceDate, using the alias name InvoiceDate
   */
  public Date getInvoiceDate() {
    return (Date)getAttributeInternal(INVOICEDATE);
  }

  /**Sets <code>value</code> as the attribute value for InvoiceDate
   */
  public void setInvoiceDate(Date value) {
    setAttributeInternal(INVOICEDATE, value);
  }

  /**Gets the attribute value for CustomerNum, using the alias name CustomerNum
   */
  public String getCustomerNum() {
    return (String)getAttributeInternal(CUSTOMERNUM);
  }

  /**Sets <code>value</code> as the attribute value for CustomerNum
   */
  public void setCustomerNum(String value) {
    setAttributeInternal(CUSTOMERNUM, value);
  }

  /**Gets the attribute value for CreatedBy, using the alias name CreatedBy
   */
  public Number getCreatedBy() {
    return (Number)getAttributeInternal(CREATEDBY);
  }

  /**Sets <code>value</code> as the attribute value for CreatedBy
   */
  public void setCreatedBy(Number value) {
    setAttributeInternal(CREATEDBY, value);
  }

  /**Gets the attribute value for CreationDate, using the alias name CreationDate
   */
  public Date getCreationDate() {
    return (Date)getAttributeInternal(CREATIONDATE);
  }

  /**Sets <code>value</code> as the attribute value for CreationDate
   */
  public void setCreationDate(Date value) {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
   */
  public Number getLastUpdatedBy() {
    return (Number)getAttributeInternal(LASTUPDATEDBY);
  }

  /**Sets <code>value</code> as the attribute value for LastUpdatedBy
   */
  public void setLastUpdatedBy(Number value) {
    setAttributeInternal(LASTUPDATEDBY, value);
  }

  /**Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
   */
  public Date getLastUpdateDate() {
    return (Date)getAttributeInternal(LASTUPDATEDATE);
  }

  /**Sets <code>value</code> as the attribute value for LastUpdateDate
   */
  public void setLastUpdateDate(Date value) {
    setAttributeInternal(LASTUPDATEDATE, value);
  }

  /**Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin
   */
  public Number getLastUpdateLogin() {
    return (Number)getAttributeInternal(LASTUPDATELOGIN);
  }

  /**Sets <code>value</code> as the attribute value for LastUpdateLogin
   */
  public void setLastUpdateLogin(Number value) {
    setAttributeInternal(LASTUPDATELOGIN, value);
  }

  /**getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, 
                                         AttributeDefImpl attrDef) throws Exception {
    switch (index) {
    case INVOICEID:
      return getInvoiceId();
    case INVOICENUM:
      return getInvoiceNum();
    case INVOICEDATE:
      return getInvoiceDate();
    case CUSTOMERNUM:
      return getCustomerNum();
    case CREATEDBY:
      return getCreatedBy();
    case CREATIONDATE:
      return getCreationDate();
    case LASTUPDATEDBY:
      return getLastUpdatedBy();
    case LASTUPDATEDATE:
      return getLastUpdateDate();
    case LASTUPDATELOGIN:
      return getLastUpdateLogin();
    case RESTINVOICELINEEO:
      return getRestInvoiceLineEO();
    default:
      return super.getAttrInvokeAccessor(index, attrDef);
    }
  }

  /**setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, 
                                       AttributeDefImpl attrDef) throws Exception {
    switch (index) {
    case INVOICEID:
      setInvoiceId((Number)value);
      return;
    case INVOICENUM:
      setInvoiceNum((String)value);
      return;
    case INVOICEDATE:
      setInvoiceDate((Date)value);
      return;
    case CUSTOMERNUM:
      setCustomerNum((String)value);
      return;
    case CREATEDBY:
      setCreatedBy((Number)value);
      return;
    case CREATIONDATE:
      setCreationDate((Date)value);
      return;
    case LASTUPDATEDBY:
      setLastUpdatedBy((Number)value);
      return;
    case LASTUPDATEDATE:
      setLastUpdateDate((Date)value);
      return;
    case LASTUPDATELOGIN:
      setLastUpdateLogin((Number)value);
      return;
    default:
      super.setAttrInvokeAccessor(index, value, attrDef);
      return;
    }
  }

  /**Gets the associated entity oracle.jbo.RowIterator
   */
  public RowIterator getRestInvoiceLineEO() {
    return (RowIterator)getAttributeInternal(RESTINVOICELINEEO);
  }

  /**Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number invoiceId) {
    return new Key(new Object[]{invoiceId});
  }
}
