package xxtf.oracle.apps.xxtf.restdemo.server;

import oracle.apps.fnd.framework.server.OAEntityDefImpl;
import oracle.apps.fnd.framework.server.OAEntityImpl;
import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RestInvoiceLineEOImpl extends OAEntityImpl {
  public static final int INVOICELINEID = 0;
  public static final int INVOICEID = 1;
  public static final int LINENUM = 2;
  public static final int DESCRIPTION = 3;
  public static final int QUANTITY = 4;
  public static final int PRICE = 5;
  public static final int LINEAMOUNT = 6;
  public static final int CREATEDBY = 7;
  public static final int CREATIONDATE = 8;
  public static final int LASTUPDATEDBY = 9;
  public static final int LASTUPDATEDATE = 10;
  public static final int LASTUPDATELOGIN = 11;
  public static final int RESTINVOICEEO = 12;


  private static OAEntityDefImpl mDefinitionObject;

  /**This is the default constructor (do not remove)
   */
  public RestInvoiceLineEOImpl() {
  }


  /**Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject() {
    if (mDefinitionObject == null) {
      mDefinitionObject = 
          (OAEntityDefImpl)EntityDefImpl.findDefObject("xxtf.oracle.apps.xxtf.restdemo.server.RestInvoiceLineEO");
    }
    return mDefinitionObject;
  }

  /**Add attribute defaulting logic in this method.
   */
  public void create(AttributeList attributeList) {
    super.create(attributeList);
    setInvoiceLineId(getOADBTransaction().getSequenceValue("XXTF_REST_INVOICE_LINES_S"));
  }

  /**Gets the attribute value for InvoiceLineId, using the alias name InvoiceLineId
   */
  public Number getInvoiceLineId() {
    return (Number)getAttributeInternal(INVOICELINEID);
  }

  /**Sets <code>value</code> as the attribute value for InvoiceLineId
   */
  public void setInvoiceLineId(Number value) {
    setAttributeInternal(INVOICELINEID, value);
  }

  /**Gets the attribute value for InvoiceId, using the alias name InvoiceId
   */
  public Number getInvoiceId() {
    return (Number)getAttributeInternal(INVOICEID);
  }

  /**Sets <code>value</code> as the attribute value for InvoiceId
   */
  public void setInvoiceId(Number value) {
    setAttributeInternal(INVOICEID, value);
  }

  /**Gets the attribute value for LineNum, using the alias name LineNum
   */
  public Number getLineNum() {
    return (Number)getAttributeInternal(LINENUM);
  }

  /**Sets <code>value</code> as the attribute value for LineNum
   */
  public void setLineNum(Number value) {
    setAttributeInternal(LINENUM, value);
  }

  /**Gets the attribute value for Description, using the alias name Description
   */
  public String getDescription() {
    return (String)getAttributeInternal(DESCRIPTION);
  }

  /**Sets <code>value</code> as the attribute value for Description
   */
  public void setDescription(String value) {
    setAttributeInternal(DESCRIPTION, value);
  }

  /**Gets the attribute value for Quantity, using the alias name Quantity
   */
  public Number getQuantity() {
    return (Number)getAttributeInternal(QUANTITY);
  }

  /**Sets <code>value</code> as the attribute value for Quantity
   */
  public void setQuantity(Number value) {
    setAttributeInternal(QUANTITY, value);
  }

  /**Gets the attribute value for Price, using the alias name Price
   */
  public Number getPrice() {
    return (Number)getAttributeInternal(PRICE);
  }

  /**Sets <code>value</code> as the attribute value for Price
   */
  public void setPrice(Number value) {
    setAttributeInternal(PRICE, value);
  }

  /**Gets the attribute value for LineAmount, using the alias name LineAmount
   */
  public Number getLineAmount() {
    return (Number)getAttributeInternal(LINEAMOUNT);
  }

  /**Sets <code>value</code> as the attribute value for LineAmount
   */
  public void setLineAmount(Number value) {
    setAttributeInternal(LINEAMOUNT, value);
  }

  /**Gets the attribute value for CreatedBy, using the alias name CreatedBy
   */
  public Number getCreatedBy() {
    return (Number)getAttributeInternal(CREATEDBY);
  }

  /**Sets <code>value</code> as the attribute value for CreatedBy
   */
  public void setCreatedBy(Number value) {
    setAttributeInternal(CREATEDBY, value);
  }

  /**Gets the attribute value for CreationDate, using the alias name CreationDate
   */
  public Date getCreationDate() {
    return (Date)getAttributeInternal(CREATIONDATE);
  }

  /**Sets <code>value</code> as the attribute value for CreationDate
   */
  public void setCreationDate(Date value) {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
   */
  public Number getLastUpdatedBy() {
    return (Number)getAttributeInternal(LASTUPDATEDBY);
  }

  /**Sets <code>value</code> as the attribute value for LastUpdatedBy
   */
  public void setLastUpdatedBy(Number value) {
    setAttributeInternal(LASTUPDATEDBY, value);
  }

  /**Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
   */
  public Date getLastUpdateDate() {
    return (Date)getAttributeInternal(LASTUPDATEDATE);
  }

  /**Sets <code>value</code> as the attribute value for LastUpdateDate
   */
  public void setLastUpdateDate(Date value) {
    setAttributeInternal(LASTUPDATEDATE, value);
  }

  /**Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin
   */
  public Number getLastUpdateLogin() {
    return (Number)getAttributeInternal(LASTUPDATELOGIN);
  }

  /**Sets <code>value</code> as the attribute value for LastUpdateLogin
   */
  public void setLastUpdateLogin(Number value) {
    setAttributeInternal(LASTUPDATELOGIN, value);
  }

  /**getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, 
                                         AttributeDefImpl attrDef) throws Exception {
    switch (index) {
    case INVOICELINEID:
      return getInvoiceLineId();
    case INVOICEID:
      return getInvoiceId();
    case LINENUM:
      return getLineNum();
    case DESCRIPTION:
      return getDescription();
    case QUANTITY:
      return getQuantity();
    case PRICE:
      return getPrice();
    case LINEAMOUNT:
      return getLineAmount();
    case CREATEDBY:
      return getCreatedBy();
    case CREATIONDATE:
      return getCreationDate();
    case LASTUPDATEDBY:
      return getLastUpdatedBy();
    case LASTUPDATEDATE:
      return getLastUpdateDate();
    case LASTUPDATELOGIN:
      return getLastUpdateLogin();
    case RESTINVOICEEO:
      return getRestInvoiceEO();
    default:
      return super.getAttrInvokeAccessor(index, attrDef);
    }
  }

  /**setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, 
                                       AttributeDefImpl attrDef) throws Exception {
    switch (index) {
    case INVOICELINEID:
      setInvoiceLineId((Number)value);
      return;
    case INVOICEID:
      setInvoiceId((Number)value);
      return;
    case LINENUM:
      setLineNum((Number)value);
      return;
    case DESCRIPTION:
      setDescription((String)value);
      return;
    case QUANTITY:
      setQuantity((Number)value);
      return;
    case PRICE:
      setPrice((Number)value);
      return;
    case LINEAMOUNT:
      setLineAmount((Number)value);
      return;
    case CREATEDBY:
      setCreatedBy((Number)value);
      return;
    case CREATIONDATE:
      setCreationDate((Date)value);
      return;
    case LASTUPDATEDBY:
      setLastUpdatedBy((Number)value);
      return;
    case LASTUPDATEDATE:
      setLastUpdateDate((Date)value);
      return;
    case LASTUPDATELOGIN:
      setLastUpdateLogin((Number)value);
      return;
    default:
      super.setAttrInvokeAccessor(index, value, attrDef);
      return;
    }
  }

  /**Gets the associated entity RestInvoiceEOImpl
   */
  public RestInvoiceEOImpl getRestInvoiceEO() {
    return (RestInvoiceEOImpl)getAttributeInternal(RESTINVOICEEO);
  }

  /**Sets <code>value</code> as the associated entity RestInvoiceEOImpl
   */
  public void setRestInvoiceEO(RestInvoiceEOImpl value) {
    setAttributeInternal(RESTINVOICEEO, value);
  }

  /**Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number invoiceLineId) {
    return new Key(new Object[]{invoiceLineId});
  }
}
