package xxtf.oracle.apps.xxtf.restdemo.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RestInvoiceLinesVORowImpl extends OAViewRowImpl {
  public static final int INVOICELINEID = 0;
  public static final int INVOICEID = 1;
  public static final int LINENUM = 2;
  public static final int DESCRIPTION = 3;
  public static final int QUANTITY = 4;
  public static final int PRICE = 5;
  public static final int LINEAMOUNT = 6;
  public static final int CREATEDBY = 7;
  public static final int CREATIONDATE = 8;
  public static final int LASTUPDATEDBY = 9;
  public static final int LASTUPDATEDATE = 10;
  public static final int LASTUPDATELOGIN = 11;

  /**This is the default constructor (do not remove)
   */
  public RestInvoiceLinesVORowImpl() {
  }

  /**Gets RestInvoiceLineEO entity object.
   */
  public RestInvoiceLineEOImpl getRestInvoiceLineEO() {
    return (RestInvoiceLineEOImpl)getEntity(0);
  }

  /**Gets the attribute value for INVOICE_LINE_ID using the alias name InvoiceLineId
   */
  public Number getInvoiceLineId() {
    return (Number) getAttributeInternal(INVOICELINEID);
  }

  /**Sets <code>value</code> as attribute value for INVOICE_LINE_ID using the alias name InvoiceLineId
   */
  public void setInvoiceLineId(Number value) {
    setAttributeInternal(INVOICELINEID, value);
  }

  /**Gets the attribute value for INVOICE_ID using the alias name InvoiceId
   */
  public Number getInvoiceId() {
    return (Number) getAttributeInternal(INVOICEID);
  }

  /**Sets <code>value</code> as attribute value for INVOICE_ID using the alias name InvoiceId
   */
  public void setInvoiceId(Number value) {
    setAttributeInternal(INVOICEID, value);
  }

  /**Gets the attribute value for LINE_NUM using the alias name LineNum
   */
  public Number getLineNum() {
    return (Number) getAttributeInternal(LINENUM);
  }

  /**Sets <code>value</code> as attribute value for LINE_NUM using the alias name LineNum
   */
  public void setLineNum(Number value) {
    setAttributeInternal(LINENUM, value);
  }

  /**Gets the attribute value for DESCRIPTION using the alias name Description
   */
  public String getDescription() {
    return (String) getAttributeInternal(DESCRIPTION);
  }

  /**Sets <code>value</code> as attribute value for DESCRIPTION using the alias name Description
   */
  public void setDescription(String value) {
    setAttributeInternal(DESCRIPTION, value);
  }

  /**Gets the attribute value for QUANTITY using the alias name Quantity
   */
  public Number getQuantity() {
    return (Number) getAttributeInternal(QUANTITY);
  }

  /**Sets <code>value</code> as attribute value for QUANTITY using the alias name Quantity
   */
  public void setQuantity(Number value) {
    setAttributeInternal(QUANTITY, value);
  }

  /**Gets the attribute value for PRICE using the alias name Price
   */
  public Number getPrice() {
    return (Number) getAttributeInternal(PRICE);
  }

  /**Sets <code>value</code> as attribute value for PRICE using the alias name Price
   */
  public void setPrice(Number value) {
    setAttributeInternal(PRICE, value);
  }

  /**Gets the attribute value for LINE_AMOUNT using the alias name LineAmount
   */
  public Number getLineAmount() {
    return (Number) getAttributeInternal(LINEAMOUNT);
  }

  /**Sets <code>value</code> as attribute value for LINE_AMOUNT using the alias name LineAmount
   */
  public void setLineAmount(Number value) {
    setAttributeInternal(LINEAMOUNT, value);
  }

  /**Gets the attribute value for CREATED_BY using the alias name CreatedBy
   */
  public Number getCreatedBy() {
    return (Number) getAttributeInternal(CREATEDBY);
  }

  /**Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy
   */
  public void setCreatedBy(Number value) {
    setAttributeInternal(CREATEDBY, value);
  }

  /**Gets the attribute value for CREATION_DATE using the alias name CreationDate
   */
  public Date getCreationDate() {
    return (Date) getAttributeInternal(CREATIONDATE);
  }

  /**Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate
   */
  public void setCreationDate(Date value) {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
   */
  public Number getLastUpdatedBy() {
    return (Number) getAttributeInternal(LASTUPDATEDBY);
  }

  /**Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
   */
  public void setLastUpdatedBy(Number value) {
    setAttributeInternal(LASTUPDATEDBY, value);
  }

  /**Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
   */
  public Date getLastUpdateDate() {
    return (Date) getAttributeInternal(LASTUPDATEDATE);
  }

  /**Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
   */
  public void setLastUpdateDate(Date value) {
    setAttributeInternal(LASTUPDATEDATE, value);
  }

  /**Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
   */
  public Number getLastUpdateLogin() {
    return (Number) getAttributeInternal(LASTUPDATELOGIN);
  }

  /**Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
   */
  public void setLastUpdateLogin(Number value) {
    setAttributeInternal(LASTUPDATELOGIN, value);
  }

  /**getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, 
                                         AttributeDefImpl attrDef) throws Exception {
    switch (index) {
    case INVOICELINEID:
      return getInvoiceLineId();
    case INVOICEID:
      return getInvoiceId();
    case LINENUM:
      return getLineNum();
    case DESCRIPTION:
      return getDescription();
    case QUANTITY:
      return getQuantity();
    case PRICE:
      return getPrice();
    case LINEAMOUNT:
      return getLineAmount();
    case CREATEDBY:
      return getCreatedBy();
    case CREATIONDATE:
      return getCreationDate();
    case LASTUPDATEDBY:
      return getLastUpdatedBy();
    case LASTUPDATEDATE:
      return getLastUpdateDate();
    case LASTUPDATELOGIN:
      return getLastUpdateLogin();
    default:
      return super.getAttrInvokeAccessor(index, attrDef);
    }
  }

  /**setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, 
                                       AttributeDefImpl attrDef) throws Exception {
    switch (index) {
    case INVOICELINEID:
      setInvoiceLineId((Number)value);
      return;
    case INVOICEID:
      setInvoiceId((Number)value);
      return;
    case LINENUM:
      setLineNum((Number)value);
      return;
    case DESCRIPTION:
      setDescription((String)value);
      return;
    case QUANTITY:
      setQuantity((Number)value);
      return;
    case PRICE:
      setPrice((Number)value);
      return;
    case LINEAMOUNT:
      setLineAmount((Number)value);
      return;
    case CREATEDBY:
      setCreatedBy((Number)value);
      return;
    case CREATIONDATE:
      setCreationDate((Date)value);
      return;
    case LASTUPDATEDBY:
      setLastUpdatedBy((Number)value);
      return;
    case LASTUPDATEDATE:
      setLastUpdateDate((Date)value);
      return;
    case LASTUPDATELOGIN:
      setLastUpdateLogin((Number)value);
      return;
    default:
      super.setAttrInvokeAccessor(index, value, attrDef);
      return;
    }
  }
}
