package xxtf.oracle.apps.xxtf.restdemo.server;

import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RestInvoiceQueryVORowImpl extends RestInvoicesVORowImpl {
  public static final int MAXATTRCONST = oracle.jbo.server.ViewDefImpl.getMaxAttrConst("xxtf.oracle.apps.xxtf.restdemo.server.RestInvoicesVO");

  /**This is the default constructor (do not remove)
   */
  public RestInvoiceQueryVORowImpl() {
  }

  /**Gets RestInvoiceEO entity object.
   */
  public RestInvoiceEOImpl getRestInvoiceEO() {
    return (RestInvoiceEOImpl)getEntity(0);
  }

  /**getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, 
                                         AttributeDefImpl attrDef) throws Exception {
    return super.getAttrInvokeAccessor(index, attrDef);
  }

  /**setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {super.setAttrInvokeAccessor(index, value, attrDef);
    return;
  }
}
